openapi: 3.0.3
info:
  title: jsapdu-over-ip Router API
  description: |
    Router service for connecting remote controllers with cardhosts.
    Enables transparent APDU command routing over the internet.
  version: 0.1.0
  contact:
    name: AokiApp
    url: https://github.com/AokiApp/jsapdu-over-ip

servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: cardhost
    description: Cardhost registration and management
  - name: controller
    description: Controller operations
  - name: health
    description: Service health checks

paths:
  /api/cardhosts:
    get:
      tags:
        - cardhost
      summary: List available cardhosts
      description: Returns list of currently connected cardhosts
      operationId: listCardhosts
      parameters:
        - name: status
          in: query
          description: Filter by connection status
          required: false
          schema:
            type: string
            enum: [connected, disconnected, all]
            default: connected
      responses:
        '200':
          description: List of cardhosts
          content:
            application/json:
              schema:
                type: object
                properties:
                  cardhosts:
                    type: array
                    items:
                      $ref: '#/components/schemas/CardhostInfo'
                  total:
                    type: integer
                    description: Total number of cardhosts
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/cardhosts/{uuid}:
    get:
      tags:
        - cardhost
      summary: Get cardhost details
      description: Returns detailed information about a specific cardhost
      operationId: getCardhost
      parameters:
        - name: uuid
          in: path
          description: Cardhost UUID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cardhost details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardhostDetails'
        '404':
          description: Cardhost not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/controller/sessions:
    post:
      tags:
        - controller
      summary: Create controller session
      description: Creates a new controller session for connecting to cardhosts
      operationId: createControllerSession
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Optional session name
                  example: "My Controller Session"
      responses:
        '201':
          description: Session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                    format: uuid
                    description: Session identifier
                  wsUrl:
                    type: string
                    description: WebSocket URL for this session
                    example: "ws://localhost:8080/ws/controller/{sessionId}"
                  expiresAt:
                    type: string
                    format: date-time
                    description: Session expiration time
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /healthz:
    get:
      tags:
        - health
      summary: Health check endpoint
      description: Returns service health status
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [UP, DOWN]
                  checks:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        status:
                          type: string
                          enum: [UP, DOWN]
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [DOWN]

components:
  schemas:
    CardhostInfo:
      type: object
      required:
        - uuid
        - status
        - connectedAt
      properties:
        uuid:
          type: string
          format: uuid
          description: Unique identifier for the cardhost
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          description: Optional friendly name for the cardhost
          example: "Office Card Reader"
        status:
          type: string
          enum: [connected, disconnected]
          description: Current connection status
        connectedAt:
          type: string
          format: date-time
          description: Timestamp when cardhost connected
        lastHeartbeat:
          type: string
          format: date-time
          description: Timestamp of last heartbeat
        capabilities:
          type: object
          description: Cardhost capabilities
          properties:
            readers:
              type: integer
              description: Number of card readers
              example: 2

    CardhostDetails:
      allOf:
        - $ref: '#/components/schemas/CardhostInfo'
        - type: object
          properties:
            readers:
              type: array
              description: List of card readers
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Reader name
                    example: "ACS ACR122U"
                  hasCard:
                    type: boolean
                    description: Whether a card is currently inserted
            statistics:
              type: object
              description: Usage statistics
              properties:
                totalCommands:
                  type: integer
                  description: Total APDU commands processed
                  example: 1234
                uptime:
                  type: integer
                  description: Uptime in seconds
                  example: 3600
                lastCommandAt:
                  type: string
                  format: date-time
                  description: Timestamp of last command

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: Error code
          example: 500
        message:
          type: string
          description: Error message
          example: "Internal server error"
        details:
          type: string
          description: Additional error details

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
